services:
  - type: web
    name: shelf-chef
    env: ruby # this app is written in ruby
    plan: free 
    buildCommand: "./bin/render-build.sh" 
    startCommand: "./bin/render-start.sh"
    envVars: 
      - key: SECRET_KEY_BASE
        generateValue: true
